swagger: "2.0"
info:
    title: Book Service
    description: Service that provides CRUD operations for a book
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /book:
        post:
            tags:
                - book
            summary: postBook book
            operationId: book#postBook
            parameters:
                - name: PostBookRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/BookPostBookRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BookPostBookResponseBodyResultOperation'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BookPostBookBadRequestResponseBody'
            schemes:
                - http
    /book/{bookID}:
        get:
            tags:
                - book
            summary: getBook book
            operationId: book#getBook
            parameters:
                - name: bookID
                  in: path
                  description: Book ID
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BookGetBookResponseBody'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BookGetBookBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BookGetBookNotFoundResponseBody'
            schemes:
                - http
    /book/{id}:
        patch:
            tags:
                - book
            summary: patchBook book
            operationId: book#patchBook
            parameters:
                - name: id
                  in: path
                  required: true
                  type: integer
                - name: PatchBookRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/BookPatchBookRequestBody'
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BookPatchBookBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BookPatchBookNotFoundResponseBody'
            schemes:
                - http
    /swagger.json:
        get:
            tags:
                - book
            summary: Download ./gen/http/openapi.json
            operationId: book#/swagger.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    BookGetBookBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: getBook_BadRequest_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookGetBookNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: getBook_NotFound_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookGetBookResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.example.book; view=default'
        type: object
        properties:
            author:
                type: string
                description: author of the book
                example: Laborum qui.
            bookCover:
                type: string
                description: cover of the book
                example:
                    - 73
                    - 115
                    - 116
                    - 101
                    - 32
                    - 99
                    - 117
                    - 109
                    - 113
                    - 117
                    - 101
                    - 32
                    - 109
                    - 111
                    - 108
                    - 101
                    - 115
                    - 116
                    - 105
                    - 97
                    - 101
                    - 32
                    - 118
                    - 111
                    - 108
                    - 117
                    - 112
                    - 116
                    - 97
                    - 116
                    - 101
                    - 115
                    - 32
                    - 114
                    - 101
                    - 112
                    - 101
                    - 108
                    - 108
                    - 97
                    - 116
                    - 32
                    - 116
                    - 101
                    - 109
                    - 112
                    - 111
                    - 114
                    - 105
                    - 98
                    - 117
                    - 115
                    - 46
                format: byte
            id:
                type: integer
                description: ID of the book
                example: 7401574212649986766
                format: int64
            publishedAt:
                type: string
                description: cover of the book
                example: Nisi nemo.
            title:
                type: string
                description: ' of the book'
                example: Et nobis enim illum culpa tempore.
        description: GetBookResponseBody result type (default view)
        example:
            author: Voluptatem aut eos.
            bookCover:
                - 67
                - 111
                - 114
                - 114
                - 117
                - 112
                - 116
                - 105
                - 32
                - 101
                - 120
                - 99
                - 101
                - 112
                - 116
                - 117
                - 114
                - 105
                - 32
                - 97
                - 117
                - 116
                - 46
            id: 4136944418154145309
            publishedAt: Sunt assumenda adipisci iste eius.
            title: Dolorem eligendi ut labore.
    BookPatchBookBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: patchBook_BadRequest_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookPatchBookNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: patchBook_NotFound_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookPatchBookRequestBody:
        title: BookPatchBookRequestBody
        type: object
        properties:
            author:
                type: string
                example: Magni quam modi.
            bookCover:
                type: string
                example:
                    - 66
                    - 101
                    - 97
                    - 116
                    - 97
                    - 101
                    - 32
                    - 112
                    - 108
                    - 97
                    - 99
                    - 101
                    - 97
                    - 116
                    - 46
                format: byte
            id:
                type: integer
                example: 2142207694530240581
                format: int64
            publishedAt:
                type: string
                example: Consequuntur molestiae et.
            title:
                type: string
                example: Et distinctio.
        description: A single book response
        example:
            author: Voluptas perspiciatis quas iure odio.
            bookCover:
                - 82
                - 101
                - 114
                - 117
                - 109
                - 32
                - 101
                - 117
                - 109
                - 46
            id: 2648768174021329261
            publishedAt: Cupiditate molestiae doloribus aliquam.
            title: Sint aut est similique nobis odit.
    BookPostBookBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: postBook_BadRequest_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookPostBookRequestBody:
        title: BookPostBookRequestBody
        type: object
        properties:
            author:
                type: string
                example: Rerum accusantium sed et consectetur.
            bookCover:
                type: string
                example:
                    - 67
                    - 111
                    - 110
                    - 115
                    - 101
                    - 113
                    - 117
                    - 97
                    - 116
                    - 117
                    - 114
                    - 32
                    - 112
                    - 111
                    - 115
                    - 115
                    - 105
                    - 109
                    - 117
                    - 115
                    - 46
                format: byte
            id:
                type: integer
                example: 4841776214913335119
                format: int64
            publishedAt:
                type: string
                example: Ratione blanditiis laudantium.
            title:
                type: string
                example: Pariatur voluptas earum eaque quo dolorem.
        description: A single book response
        example:
            author: Quia et voluptate quasi.
            bookCover:
                - 69
                - 114
                - 114
                - 111
                - 114
                - 32
                - 113
                - 117
                - 105
                - 115
                - 32
                - 113
                - 117
                - 105
                - 97
                - 32
                - 105
                - 110
                - 46
            id: 1020012904780506360
            publishedAt: Reprehenderit amet dolor aut voluptas eum sed.
            title: Et quia corporis nesciunt suscipit ipsam.
        required:
            - title
            - author
    BookPostBookResponseBodyResultOperation:
        title: 'Mediatype identifier: application/vnd.goa.example.book; view=resultOperation'
        type: object
        properties:
            id:
                type: integer
                description: ID of the book
                example: 3977113922250740697
                format: int64
        description: PostBookResponseBody result type (resultOperation view) (default view)
        example:
            id: 5254078690538044943
